config/routes.rb
FirehoseAppHbs::Application.routes.draw do

   root 'static_pages#index'
   resources :pics

end

app/models/pic.rb
class Pic < ActiveRecord::Base
	mount_uploader :image, ImageUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pics_controller.rb
class PicsController < ApplicationController

	def index
		@pics = Pic.all
	end

	def new
		@pic = Pic.new
	end

	def create
		# Format is like: Pic.create(:title => "omg", ...)
		Pic.create(pic_params)
		redirect_to pics_path
	end

	private

	def pic_params
		params.require(:pic).permit(:title, :location, :message, :image)

	end


end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

	def index
	end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pics_helper.rb
module PicsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FirehoseAppHbs</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="navbar navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
 
      <!-- .btn-navbar is used as the toggle for collapsed navbar content -->
      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
 
      <!-- Be sure to leave the brand out there if you want it shown -->
	  <%= link_to "It's me, Nate Ie", root_path, :class => 'brand' %>	    

 
      <!-- Everything you want hidden at 940px or less, place within here -->
      <div class="nav-collapse collapse">
        <!-- .nav, .navbar-search, .navbar-form, etc -->

      	<ul class="nav">	
      		<li>    
      			<%= link_to 'My Pics', pics_path %>	    
      		</li>
      		<li>    
      			<%= link_to '+Pic', new_pic_path %>	    
      		</li>    
    	</ul>
      </div>
 
    </div>
  </div>
</div>


<%= yield %>

</body>
</html>

app/views/pics/index.html.erb
<% @pics.each_slice(2) do |slice| %>
	<div class="row">
		<% slice.each do |pic| %>
			<div class="smurfy span6 text-center">
					<h1 class="custom-h1">
						<%= pic.title %>
					</h1>
					<br />
					<h2>
						Location: <%= pic.location %>
					</h2>
					<br />
						<%= image_tag pic.image %>
					<br />
						<%= pic.message %>
					
			</div>
	
		<% end %>
	</div>
<% end %>

app/views/pics/new.html.erb
<div class="smurfy span5 offset4 text-center">

	<h1 class="custom-h1">
		Submit a favorite pic!
	</h1>
	<br/>

	<%= simple_form_for @pic do |f| %>
		<%= f.input :title, label: "What's this picture called?", placeholder: "Midnight in Paris" %>
		<%= f.input :location, label: "Where was this?", placeholder: "France" %>
		<%= f.input :message, label: "Thoughts?", placeholder: "What a night!" %>
		<%= f.input :image, label: "Find your pic" %>
		<br/>
		<%= f.submit "Add Pic", :class => 'btn btn-success btn-large' %>

	<% end %>
</div>

app/views/static_pages/index.html.erb
<!-- H1 stuff is super important for SEO -->

<br/>
<br/>

<div class="span6 offset1 smurfy text-center">


	<h1 class='custom-h1'>
		Hey, I'm Nate. <br/>
		From OC and OC.
	</h1>

	<br/>

	<h2>
		Let's go adventuring!
	</h2>

	<br/>

	<%= link_to 'Launch', pics_path, :class => 'btn btn-success btn-large' %>	

</div>